### ISSUE TITLE
in the new update from the sf1000 there isn a udp option

### ISSUE THREAD

**Issue by flailyyy** [ducng99/SimHub-SF1000-UDP#23]
You can't choose or activate the UDP option, and the display from the wheel is just black when I launch Assetto Corsa, and I don't know how to do it another way aside from the instructions from you.

**Comment by ducng99** [comment]
There is no activate button, as long as it is highlighted then UDP will be used. You can check on the WiFi screen if UDP shows "20777", that means the wheel is reading from UDP
![image](https://github.com/ducng99/SimHub-to-F12020-UDP/assets/49080794/bc893ec1-ebd2-44a4-9bbe-bccbdcd82f05)

After that you can follow instructions how to configure this plugin: https://github.com/ducng99/SimHub-to-F12020-UDP#plugin-config

Let me know if it still doesn't work for you after that

**Comment by ducng99** [comment]
Sorry, I think I misunderstood you. I'm updating my wheel's firmware now to check, it does seem from the screenshot they removed the UDP screen in firmware v6.*

**Comment by ducng99** [comment]
Just tested, this plugin is still working fine. On firmware v6.27 the UDP configuration screen is gone, but UDP is enabled by default.
I will update my instructions for this.

You can configure this plugin in SimHub with the IP shows on your wheel like normal and it will work

**Comment by flailyyy** [comment]
Yes, I tried to do that anyway but nothing is displayed on my screen. It
would be good if you make New instructions or a video and explained how it
works. Nothing ever works for me straight away.

thanks for writing back.

Thomas Nguyen ***@***.***> schrieb am Di., 26. Dez. 2023,
03:13:

**Comment by flailyyy** [comment]
I tried to run it, but it still does not work. I don't know what I did wrong. I do the same thing as in the instructions, and it still doesn't want to work. Can you show how to run a game or how I set up the dash because there are only 5 options and no one is the right one Do I need a mod or so?

**Comment by ducng99** [comment]
I made this simple video showing the steps, it really just what already mentioned in [configuration section](https://github.com/ducng99/SimHub-to-F12020-UDP#configuration)
https://youtu.be/N9ztAimSXZk

If it's still not working for you, flick me a message on discord `maxhyt` and we'll figure something out

**Comment by macreiben-dev** [comment]
Will test that @ducng99.

**Comment by ducng99** [comment]
Happy new year all!
@flailyyy Just wondering if you are still having this issue? More than happy to help or it you've managed to solve it, I'll close this issue. Cheers
