### ISSUE TITLE
Error message when launching simhub

### ISSUE THREAD

**Issue by Bear13583** [ducng99/SimHub-SF1000-UDP#27]
![20240215_102649](https://github.com/ducng99/SimHub-SF1000-UDP/assets/160122862/1d3a6ea6-0e8b-4098-ba54-69e3266add4c)

Hi, I have updated the registry files to enable logging but no I get this error message when I try to launch sim hub? Any ideas what I have done wrong? 

My wheel is using the latest firmware and I have put your dll file into the main simhub registry. Anyhelp would be greatly appreciated

**Comment by ducng99** [comment]
Thanks for reporting this, I'll have a look now

**Comment by ducng99** [comment]
Can you confirm what is your SimHub version please?
Would be good if you can attach the file `SimHubWPF.exe.Config` in your SimHub folder too.

**Comment by Bear13583** [comment]
version 7.4.23 
and sorry but here is the contents of the config file, it wont let me attach it.....

**Comment by Bear13583** [comment]
<?xml version="1.0" encoding="utf-8"?>
<configuration>
	<configSections>
		<sectionGroup name="userSettings" type="System.Configuration.UserSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">
			<section name="SimHubWPF.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" allowExeDefinition="MachineToLocalUser" requirePermission="false" />
		</sectionGroup>
		<section name="log4net" type="log4net.Config.Log4NetConfigurationSectionHandler, log4net" />
	</configSections>
	<runtime>
		<enforceFIPSPolicy enabled="false" />
		<AppContextSwitchOverrides value="Switch.System.IO.Ports.DoNotCatchSerialStreamThreadExceptions=false;Switch.System.Windows.Controls.Grid.StarDefinitionsCanExceedAvailableSpace=true" />
		<legacyCorruptedStateExceptionsPolicy enabled="true" />
		<loadFromRemoteSources enabled="true" />
		<gcConcurrent enabled="true" />
		
		<legacyUnhandledExceptionPolicy enabled="1" />
		<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
			<probing privatePath="x86" />


			<dependentAssembly>
				<assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-12.0.0.0" newVersion="12.0.0.0" />
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="System.ValueTuple" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-4.0.3.0" newVersion="4.0.3.0" />
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="Google.Api.Gax" publicKeyToken="3ec5ea7f18953e47" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-3.5.0.0" newVersion="3.5.0.0" />
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="Google.Api.Gax.Grpc" publicKeyToken="3ec5ea7f18953e47" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-3.5.0.0" newVersion="3.5.0.0" />
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="Google.Api.Gax.Grpc.GrpcCore" publicKeyToken="3ec5ea7f18953e47" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-3.5.0.0" newVersion="3.5.0.0" />
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="Google.Apis.Auth" publicKeyToken="4b01fa6e34db77ab" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-1.53.0.0" newVersion="1.53.0.0" />
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="System.Buffers" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-4.0.3.0" newVersion="4.0.3.0" />
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="Microsoft.Owin.Security" publicKeyToken="31bf3856ad364e35" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-3.1.0.0" newVersion="3.1.0.0" />
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="Microsoft.Owin" publicKeyToken="31bf3856ad364e35" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" />
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="System.Web.Cors" publicKeyToken="31bf3856ad364e35" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-5.2.3.0" newVersion="5.2.3.0" />
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="log4net" publicKeyToken="669e0ddf0bb1aa2a" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-2.0.8.0" newVersion="2.0.8.0" />
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="System.Numerics.Vectors" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-4.1.4.0" newVersion="4.1.4.0" />
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="System.Memory" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-4.0.1.1" newVersion="4.0.1.1" />
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="Microsoft.Win32.Registry" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-4.1.3.0" newVersion="4.1.3.0" />
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="System.Security.Principal.Windows" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-4.1.3.0" newVersion="4.1.3.0" />
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="System.ComponentModel.Annotations" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-4.2.1.0" newVersion="4.2.1.0" />
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="System.Collections.Immutable" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-1.2.3.0" newVersion="1.2.3.0" />
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="System.Security.Cryptography.Cng" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-4.3.1.0" newVersion="4.3.1.0" />
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-4.0.4.1" newVersion="4.0.4.1" />
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="Microsoft.Extensions.Primitives" publicKeyToken="adb9793829ddae60" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-2.2.0.0" newVersion="2.2.0.0" />
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="Microsoft.Extensions.FileProviders.Abstractions" publicKeyToken="adb9793829ddae60" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-2.2.0.0" newVersion="2.2.0.0" />
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="Microsoft.AspNetCore.Http.Abstractions" publicKeyToken="adb9793829ddae60" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-2.2.0.0" newVersion="2.2.0.0" />
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="Microsoft.Extensions.DependencyInjection.Abstractions" publicKeyToken="adb9793829ddae60" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-2.2.0.0" newVersion="2.2.0.0" />
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="Microsoft.Extensions.Options" publicKeyToken="adb9793829ddae60" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-2.2.0.0" newVersion="2.2.0.0" />
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="Microsoft.Extensions.Logging.Abstractions" publicKeyToken="adb9793829ddae60" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-2.2.0.0" newVersion="2.2.0.0" />
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="Microsoft.Net.Http.Headers" publicKeyToken="adb9793829ddae60" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-2.2.0.0" newVersion="2.2.0.0" />
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="Microsoft.AspNetCore.Http.Features" publicKeyToken="adb9793829ddae60" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-2.2.0.0" newVersion="2.2.0.0" />
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="Microsoft.AspNetCore.Http.Extensions" publicKeyToken="adb9793829ddae60" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-2.2.0.0" newVersion="2.2.0.0" />
			</dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="System.Reflection.Metadata" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-1.4.3.0" newVersion="1.4.3.0" />
			</dependentAssembly>
		</assemblyBinding>
	</runtime>
	<appSettings>
		<add key="F1GearingProcesses" value="F1_2015;F1_2011;F1_2016;F1_2017" />
		<add key="AssettoCorsaProcesses" value="ACS;ACS_x86;acs_dmm;AssettoCorsa" />
		<add key="PCarsProcesses" value="pCARS64;pCARS" />
		<add key="PCars2Processes" value="pCARS2AVX;pCARS2" />
		<add key="PCars3Processes" value="pCARS3" />
		<add key="IRacingProcesses" value="iRacingSim64;iRacingSim;iRacingSimDX11;iRacingSim64DX11" />
		<add key="CodemastersDirtShowdownProcesses" value="showdown;showdown_avx" />
		<add key="CodemastersDirt2Processes" value="dirt2_game;dirt2" />
		<add key="CodemastersDirt3Processes" value="dirt3_game;dirt3" />
		<add key="CodemastersDirt4Processes" value="dirt4" />
		<add key="CodemastersDirtRallyProcesses" value="drt" />
		<add key="CodemastersDirtRally2Processes" value="dirtrally2" />
		<add key="CodemastersDirtProcesses" value="dirt" />
		<add key="CodemastersRacedriverGridProcesses" value="grid" />
		<add key="CodemastersGrid2019Processes" value="Grid_dx12" />
		<add key="CodemastersGridLegendsProcesses" value="GridLegends" />
		<add key="CodemastersGrid2Processes" value="grid2_avx;grid2" />
		<add key="CodemastersGridAutosportProcesses" value="GRIDAutosport_avx;GRIDAutosport" />
		<add key="F12012Processes" value="F1_2012" />
		<add key="F12013Processes" value="F1_2013" />
		<add key="F12014Processes" value="F1_2014" />
		<add key="F12015Processes" value="F1_2015" />
		<add key="F12016Processes" value="F1_2016" />
		<add key="F12017Processes" value="F1_2017" />
		<add key="F12018Processes" value="F1_2018" />
		<add key="F12019Processes" value="F1_2019;F1_2019_dx12" />
		<add key="F12020Processes" value="F1_2020;F1_2020_dx12" />
		<add key="F12021Processes" value="F1_2021;F1_2021_dx12" />
		<add key="ETS2Processes" value="eurotrucks2" />
		<add key="ATSProcesses" value="amtrucks" />
		<add key="ATSFunbitProcesses" value="eurotrucks2" />
		<add key="ETS2FunbitProcesses" value="amtrucks" />
		<add key="RFACTOR1Processes" value="Rfactor" />
		<add key="AutomobilistaProcesses" value="AMS" />
		<add key="Automobilista2Processes" value="AMS2;AMS2AVX" />
		<add key="RRREProcesses" value="RRRE;RRRE64" />
		<add key="RFACTOR2Processes" value="Rfactor2" />
		<add key="RFACTOR2SpectatorProcesses" value="Rfactor2" />
		<add key="LFSProcesses" value="LFS" />
		<add key="WARTHUNDERProcesses" value="aces" />
		<add key="RBRProcesses" value="RichardBurnsRally_SSE;RichardBurnsRally_NoSSE;RichardBurnsRally" />
		<add key="RealRallyProcesses" value="Real_Rally_Manager;RichardBurnsRally_SSE;RichardBurnsRally_NoSSE;RichardBurnsRally" />
		<add key="SIMBINRACE07Processes" value="Race;Race_Steam" />
		<add key="SIMBINRACEWTCCProcesses" value="Race;Race_Steam" />
		<add key="SIMBINGTLEGENDSProcesses" value="GTL" />
		<add key="TrackmaniaProcesses" value="maniaplanet" />
		<add key="TrackmaniaTurboProcesses" value="trackmaniaturbo" />
		<add key="CSGOProcesses" value="csgo" />
		<add key="DOTA2Processes" value="dota2" />
		<add key="BeamNgProcesses" value="BeamNG.drive.x64;BeamNG.drive.x86;BeamNG.drive.x86.ui;BeamNG.drive.x64.ui;BeamNG.drive" />
		<add key="FM7Processes" value="forzamotorsport7" />
		<add key="FH4Processes" value="forzahorizon4" />
		<add key="FH5Processes" value="forzahorizon5" />
		<add key="BMWM3CHALLENGEProcesses" value="bmw" />
		<add key="AssettoCorsaCompetizioneProcesses" value="AC2-Win64-Shipping;acc" />
		<add key="MotoGP18Processes" value="motogp18-Win64-Shipping;MotoGP18" />
		<add key="GRallyProcesses" value="gRally;gRallySim" />
		<add key="KartKraftProcesses" value="project_k;project_k-Win64-Shipping" />
		<add key="FURIDASHIDriftCyberSportProcesses" value="Furidashi" />
		<add key="KartRacingProProcesses" value="kart" />
		<add key="NoLimits2Processes" value="nolimits2stm" />
		<add key="OMSI2Processes" value="Omsi" />
		<add key="SIMBINGTRProcesses" value="GTR" />
		<add key="SIMBINGTR2Processes" value="GTR2" />
		<add key="NASCARHeat4Processes" value="NASCARHeat4" />
		<add key="NASCARHeat5Processes" value="NASCARHeat5" />
		<add key="FernbusSimulatorProcesses" value="Fernbus-Win64-Shipping" />
		<add key="TMLTheBusProcesses" value="TheBus" />
		<add key="SRXTheGameProcesses" value="SRXRacing" />

		<add key="StockCarExtremeProcesses" value="GSC" />
		<add key="FarmingSimulator19Processes" value="FarmingSimulator2019" />
		<add key="FarmingSimulator22Processes" value="FarmingSimulator2022" />
		<add key="FlightSimulator2020Processes" value="FlightSimulator" />
		<add key="TouristBusSimulatorProcesses" value="TouristBusSimulator" />
		<add key="TrainSimulatorProcesses" value="RailWorks64" />
		<add key="TonyStewartsSprintCarRacingProcesses" value="SprintCarRacing" />
		<add key="TonyStewartsAllAmericanRacingProcesses" value="AllAmericanRacing" />
		
		<add key="GPBikesProcesses" value="core" />
		<add key="MXBikesProcesses" value="gpbikes" />
		<add key="WRCXProcesses" value="WRC9;WRC8;WRC7" />
		<add key="WRC10Processes" value="WRC10" />
		<add key="ACCEnableBroadcastFeature" value="true" />
		<add key="ClientSettingsProvider.ServiceUri" value="" />
	</appSettings>
	<startup>
		<supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.8" />
	</startup>
	<log4net>
		<appender name="ConsoleAppender" type="log4net.Appender.DebugAppender">
			<layout type="log4net.Layout.PatternLayout">
				<param name="Header" value="[Header]\r\n" />
				<param name="Footer" value="[Footer]\r\n" />
				<param name="ConversionPattern" value="[%date] %level - %message%newline" />
			</layout>
		</appender>
		<appender name="EventAppender" type="WoteverCommon.WPF.Log.LogDispatcherAppender, WoteverCommon">
			<layout type="log4net.Layout.PatternLayout">
				<param name="Header" value="[Header]\r\n" />
				<param name="Footer" value="[Footer]\r\n" />
				<param name="ConversionPattern" value="[%date] %level - %message%newline" />
			</layout>
		</appender>
		<appender name="RollingFileAppender" type="log4net.Appender.RollingFileAppender">
			<file value="Logs\SimHub.log" />
			
			<appendToFile value="false" />
			<rollingStyle value="Size" />
			<maxSizeRollBackups value="20" />
			<maximumFileSize value="3MB" />
			<staticLogFileName value="true" />
			<layout type="log4net.Layout.PatternLayout">
				<conversionPattern value="[%date] %level - %message%newline" />
			</layout>
		</appender>
		<root>
			<level value="INFO" />
			
			<appender-ref ref="ConsoleAppender" />
			<appender-ref ref="EventAppender" />
			<appender-ref ref="RollingFileAppender" />
		</root>
	</log4net>
	<userSettings>
		<SimHubWPF.Properties.Settings>
			<setting name="LastGame" serializeAs="String">
				<value />
			</setting>
			<setting name="StartMinimized" serializeAs="String">
				<value>False</value>
			</setting>
			<setting name="Developper" serializeAs="String">
				<value>False</value>
			</setting>
			<setting name="AppThemeName" serializeAs="String">
				<value>BaseLight</value>
			</setting>
			<setting name="AccentName" serializeAs="String">
				<value>Blue</value>
			</setting>
			<setting name="AutoDetectGame" serializeAs="String">
				<value>True</value>
			</setting>
			<setting name="License" serializeAs="String">
				<value />
			</setting>
			<setting name="AdvancedLogging" serializeAs="String">
				<value>False</value>
			</setting>
			<setting name="RemoteServer" serializeAs="String">
				<value />
			</setting>
			<setting name="UseMphAsLocal" serializeAs="String">
				<value>False</value>
			</setting>
			<setting name="MinimizeInTray" serializeAs="String">
				<value>True</value>
			</setting>
			<setting name="ShowRefreshRate" serializeAs="String">
				<value>False</value>
			</setting>
			<setting name="HigherPriority" serializeAs="String">
				<value>False</value>
			</setting>
			<setting name="EnableNetworking" serializeAs="String">
				<value>False</value>
			</setting>
			<setting name="EnableWebPluginSync" serializeAs="String">
				<value>False</value>
			</setting>
			<setting name="RunAsAdmin" serializeAs="String">
				<value>False</value>
			</setting>
			<setting name="AllowNonCertified" serializeAs="String">
				<value>False</value>
			</setting>
			<setting name="PaneOpened" serializeAs="String">
				<value>True</value>
			</setting>
			<setting name="LocalPressureUnit" serializeAs="String">
				<value>0</value>
			</setting>
			<setting name="UseATBestWhenNoSessionBest" serializeAs="String">
				<value>False</value>
			</setting>
			<setting name="DiscardAdminAlert" serializeAs="String">
				<value>False</value>
			</setting>
			<setting name="EnableDirt3CompleteEditionFix" serializeAs="String">
				<value>False</value>
			</setting>
			<setting name="RestartAsNetwork" serializeAs="String">
				<value>False</value>
			</setting>
			<setting name="LocalFuelUnit" serializeAs="String">
				<value>0</value>
			</setting>
			<setting name="LeaderBoardGapMode" serializeAs="String">
				<value>0</value>
			</setting>
			<setting name="LocalTemperatureUnit" serializeAs="String">
				<value>0</value>
			</setting>
			<setting name="SimHubWebPort" serializeAs="String">
				<value>8888</value>
			</setting>
			<setting name="Culture" serializeAs="String">
				<value />
			</setting>
			<setting name="EnableReplayVideo" serializeAs="String">
				<value>True</value>
			</setting>
			<setting name="ReplayVideoFPS" serializeAs="String">
				<value>20</value>
			</setting>
			<setting name="UIScale" serializeAs="String">
				<value>100</value>
			</setting>
			<setting name="LastTabShown" serializeAs="String">
				<value />
			</setting>
			<setting name="StartMode" serializeAs="String">
				<value>0</value>
			</setting>
			<setting name="StartupPlugin" serializeAs="String">
				<value />
			</setting>
			<setting name="ReplayPath" serializeAs="String">
				<value />
			</setting>
			<setting name="UseCustomReplayPath" serializeAs="String">
				<value>False</value>
			</setting>
			<setting name="HideCarSettings" serializeAs="String">
				<value>False</value>
			</setting>
			<setting name="CloseInTray" serializeAs="String">
				<value>False</value>
			</setting>
			<setting name="SoundVolume" serializeAs="String">
				<value>100</value>
			</setting>
			<setting name="PreventSimhubFocusWhenGameIsFocused" serializeAs="String">
				<value>False</value>
			</setting>
			<setting name="GameVolumeChangeSteps" serializeAs="String">
				<value>10</value>
			</setting>
			<setting name="SystemVolumeChangeSteps" serializeAs="String">
				<value>10</value>
			</setting>
			<setting name="HighPrecisionGameReaderClock" serializeAs="String">
				<value>True</value>
			</setting>
			<setting name="FuelComputationMode" serializeAs="String">
				<value>1</value>
			</setting>
			<setting name="UseOnlineMaps" serializeAs="String">
				<value>False</value>
			</setting>
			<setting name="MapSourcePriority" serializeAs="String">
				<value>0</value>
			</setting>
			<setting name="MapAutomaticScore" serializeAs="String">
				<value>True</value>
			</setting>
			<setting name="Migrated" serializeAs="String">
				<value>False</value>
			</setting>
		</SimHubWPF.Properties.Settings>
	</userSettings>
	<system.web>
		<membership defaultProvider="ClientAuthenticationMembershipProvider">
			<providers>
				<add name="ClientAuthenticationMembershipProvider" type="System.Web.ClientServices.Providers.ClientFormsAuthenticationMembershipProvider, System.Web.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" serviceUri="" />
			</providers>
		</membership>
		<roleManager defaultProvider="ClientRoleProvider" enabled="true">
			<providers>
				<add name="ClientRoleProvider" type="System.Web.ClientServices.Providers.ClientRoleProvider, System.Web.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" serviceUri="" cacheTimeout="86400" />
			</providers>
		</roleManager>
		<httpHandlers>
			<add verb="*" type="Nancy.Hosting.Aspnet.NancyHttpRequestHandler" path="*" />
		</httpHandlers>
	</system.web>
	<system.webServer>
		<validation validateIntegratedModeConfiguration="false" />
		<httpErrors existingResponse="PassThrough" />
		<handlers>
			<add name="Nancy" verb="*" type="Nancy.Hosting.Aspnet.NancyHttpRequestHandler" path="*" />
		</handlers>
	</system.webServer>
</configuration>

**Comment by ducng99** [comment]
Thanks, that's all good.

That version is way too old now, you should get the latest version here if you can: https://www.simhubdash.com/download-2/
I can only keep supporting latest version only - last tested with 9.1.18 but should work with 9.*

**Comment by Bear13583** [comment]
OK didn't realise it was so outdated! Just updating it now

**Comment by Bear13583** [comment]
Sorted, thanks mate

**Comment by Bear13583** [comment]
Sorted thanks mate
