### ISSUE TITLE
No display on my Thrustmaster SF1000 steering wheel

### ISSUE THREAD

**Issue by Megadams79** [ducng99/SimHub-SF1000-UDP#28]
Good morning,
I followed the entire procedure as indicated unfortunately I have no display on my Thrusmaster SF1000.
Thank you in advance for your help
![Capture d'écran 2024-03-01 143757](https://github.com/ducng99/SimHub-SF1000-UDP/assets/161846670/b8db2c97-2f3a-4a9d-af17-e32263770058)

**Comment by ducng99** [comment]
Hi @Megadams79

That IP looks a bit strange, are you sure that's the one shown **on the wheel's screen**?
Most of the time it shows 192.168.*.* or 10.*.*.* or 172.*.*.*

If you can provide some pics of the wheel screen too that would be great.

And can you attach the SimHub log file here (SimHub -> System log -> Open logs folder, and drop the file SimHub.1.txt in here)

Thanks

**Comment by Megadams79** [comment]
Hello, thank you for the response
Attached here are the requested items.
![429785976_3861750110737375_6614805502485341624_n](https://github.com/ducng99/SimHub-SF1000-UDP/assets/161846670/1ba34353-f8d6-4d5b-948d-6a4098e2be8e)
[SimHub.1.txt](https://github.com/ducng99/SimHub-SF1000-UDP/files/14468377/SimHub.1.txt)

**Comment by ducng99** [comment]
Thanks for that, you'll need to connect the wheel to your home's Wi-Fi first.

If on Android, you can follow this guide: https://ts.thrustmaster.com/download/accessories/Manuals/SF1000/Android_FWheel_Add-On_Ferrari_SF1000Edition_Connection_Tutorial_EN.pdf

Or iOS: https://ts.thrustmaster.com/download/accessories/Manuals/SF1000/iOS_FWheel_Add-On_Ferrari_SF1000Edition_Connection_Tutorial_EN.pdf

After that you can follow from step 2 again to set up the plugin: https://github.com/ducng99/SimHub-SF1000-UDP#2-plugin-config

Let me know if you still have troubles setting it up. Cheers

**Comment by Megadams79** [comment]
Thank you for your help, The wheel connects well to my home network but unfortunately the IP address does not change and after a certain time it disconnects
![429792417_935810631226524_7588845857309601508_n](https://github.com/ducng99/SimHub-SF1000-UDP/assets/161846670/76993a1b-3954-4e0c-9945-0d1dfc1e63d5)

**Comment by ducng99** [comment]
Can you try unplugging the base and reconnect again?
You can also try turning Wi-Fi off and on (turn the middle knob to highlight the switch, then press to toggle it)

**Comment by Megadams79** [comment]
I have already tried several times and it does not correct this problem. :(

**Comment by ducng99** [comment]
Yeah that's really strange, I would suggest contacting Thrustmaster for support.
From what I can see there is no factory reset button on the wheel unfortunately.

**Comment by Megadams79** [comment]
Yes I will contact them to explain the problem, thank you for your help I will keep you informed
Have a good weekend and good game to you ;)

**Comment by ducng99** [comment]
You too! I'll leave this issue open for now

**Comment by Megadams79** [comment]
Everything works correctly, I restarted my internet box and that solved the problem.
Many thanks again for your help, good game ;)

**Comment by ducng99** [comment]
Awesome! Enjoy the game!
