### ISSUE TITLE
Connecting through a mesh wifi extension 

### ISSUE THREAD

**Issue by Bear13583** [ducng99/SimHub-SF1000-UDP#37]
Hi mate, great work! I have moved my pc out into the shed beyond the range of the house wifi. The shed has an ethernet port connected to the router in the house. 

I have added a mesh terminal to the ehernet port in the shed and my pc is plugged into that and my sf100 is connected to the mesh WiFi.

My problem is that now the wheel isn't getting any udp data so the ferrari/tm logo screen is all I get. Is this because simhub still gets the house ip address where as the wheel is on the new one?

I have changed the ip in your simhub plugin and the udp port is still 20777 on both.

Any ideas??

**Comment by ducng99** [comment]
As long as the wheel and your PC are on the same network, it should work. But sounds like there could be some sort of configuration that's blocking connection from/to PC and wheel.

On your PC, can you ping your wheel? Open cmd.exe and run
```bat
ping <wheel's IP>
```
and see if it returns and success response.
If you only get "Response timed out" then the PC cannot "see" the wheel on the network.

Maybe try plugging your PC directly to ethernet port in your shed's, without the mesh terminal and see if it works?

**Comment by Bear13583** [comment]
Hi Thomas. The ping request did indeed time out. When I had the pc and wheel in the house it all worked great. Not sure what I have done wrong now it's all connected to the mesh in the shed

**Comment by ducng99** [comment]
Sorry I can't help you much here, there are so many things that can be a factor of this - hard to know without physically be there 😅. I'd suggest searching for your mesh configuration, IP, subnet, router's configuration.

I will close this as it's not related to the plugin.
