### ISSUE TITLE
Dashbord shows but no data

### ISSUE THREAD

**Issue by Donatien59** [ducng99/SimHub-SF1000-UDP#38]
Hello

I follow all the steps except "4.you know what to do next". When i launch the game the wheel dashboard is shown but i cannot have any data on it.
My wheel is connected to wifi that is OK!  UDP is set to 20777
I launch the game through simhub, i installed the plugin and put the correct IP.
The wheel firmware is the last one, i think is why i do not have the screen anymore with UDP OFF or codemaster F1 2020.
It is the first time i use the Visual studio so i may have made a mistake there but i go the dll file in release folder.
I supposed it was a plugin for LMU so i put it in plugin file and I enable it in custompluginvariables

 - SimHub version: [e.g. 9.3.9]
 - Plugin version [e.g. 2.0.1]

Thank you in advance

**Comment by ducng99** [comment]
Hi @Donatien59 

You don't have to follow the "Building" instructions - that section is just for developers who want to contribute to this plugin. Apologies if this is confusing, I'll add a note there to make it clear.

But it seems you have the plugin installed correctly anyway which you've configured the correct IP in SimHub.

A couple questions to narrow it down:
1. Which game are you trying to run?
2. What is the IP of your wheel?

**Comment by Donatien59** [comment]
Hello,

Thank you for your answer.

I would like to use it for LMU.
The wheel IP is 192.168.1.13, it is the one i put in simhub also.

I think that sim hub is making the dashboard to show but do not send any datas.

**Comment by ducng99** [comment]
That IP looks good.

To test if your PC can connect to the wheel, can you run this command using `cmd` (search just for it in Windows):
```batch
ping 192.168.1.13
```
and let me know if it shows "Request timed out" or not.

**Comment by Donatien59** [comment]
![image](https://github.com/user-attachments/assets/a932c83d-4c7b-4926-8faf-be7debc470fa)

**Comment by ducng99** [comment]
Yes, as long as the game is configured to work with SimHub.

Can you check if LMU is configured correctly?
I'm using F1 24 as an example:

![image](https://github.com/user-attachments/assets/cbca6326-c778-450c-a4b8-1dbb9f3d574d)

![image](https://github.com/user-attachments/assets/a1612466-b0e5-4380-a24d-66b2646b9313)

There is also some instructions link there which you can follow if SimHub can't automatically configure the game

**Comment by ducng99** [comment]
Also noticed this in SimHub:
![image](https://github.com/user-attachments/assets/ac84ed00-58bb-432d-b182-7912ce9ebf0a)

I don't have the game so can't test it unfortunately.

I would suggest if you can test with another game (Assetto Corsa) and see if it works - if you do so, please select the game in "Dashboard" screen first then launch the game

**Comment by Donatien59** [comment]
I think there is the problem :

![image](https://github.com/user-attachments/assets/0736cb8e-5056-427f-984e-28c88ecbd805)

It seems it is not planned to send telemetry, while in ACC and F1 2024 it proposed some UDP for telemetry, there is nothing there :/

**Comment by Donatien59** [comment]
In fact, sorry for disturbing, The wheel is workng natively in LMU since June update and i just had to push to ON 2 settings in the calibrate menu.

I feel a bit dumb but thank you for the time you spent with me :) .

Have a nice day

**Comment by ducng99** [comment]
Nope, that means it's configured correctly. SimHub doesn't **read** UDP from LMU, hence there is no config there.

LMU --> SimHub ✅
SimHub --> This plugin --> SF1000 ❌

I meant [Assetto Corsa](https://store.steampowered.com/app/244210/Assetto_Corsa/) the og version, not ACC, which doesn't have native support. But I don't think you have the game then 😅

This is really odd. I've just released a new version [v2.0.2](https://github.com/ducng99/SimHub-SF1000-UDP/releases/tag/v2.0.2) if you want to test it out. Low chance of fixing it though

**Comment by ducng99** [comment]
Oh I think that's why, maybe the wheel tries to read data natively from the game, and just ignoring data from my plugin.

There is that toggle "Only run if..." - once you switch it **off**, the plugin should take priority.

But hey, glad it's working for you! If you have another unsupported game then now you have this plugin!

**Comment by Donatien59** [comment]
Yeah sure, i will try for rF2 later, it should work !
